### ISSUE TITLE
File populated by xlsx-populate can not open with Excel

### ISSUE THREAD

**Issue by liji123** [dtjohnson/xlsx-populate#157]
I have a template xlsm file and I use this library to populate some data. However, my template file cannot open with Excel after xlsx-populate edited. Excel prompts:
![image](https://user-images.githubusercontent.com/14195451/44500223-246c3800-a6ba-11e8-9796-60764701c2fe.png)
After clicking "Yes", all cell format are lost, and Excel prompts "Removed Part: /xl/styles.xml part with XML error.  (Styles) Load error. Line 1, column 0."
According to my resarch, this is due to wrong handing for paticular cell style by xlsx-populate. When setting a cell style to horizontal center, xlsx-populate will append `<alignment horizontal="center"/>` after original cell style <protection locked="0"/>, look like this:
```
<xf numFmtId="0" fontId="8" fillId="5" borderId="1" xfId="0" applyFill="1" applyProtection="1" applyFont="1" applyBorder="1">
	<protection locked="0"/>
	<alignment horizontal="center"/>
</xf>
```
But unfortunately, it seems Excel expects all cell format property are located before `<protection locked="0"/>`. 
If switch their positions like this:
```
<xf numFmtId="0" fontId="8" fillId="5" borderId="1" xfId="0" applyFill="1" applyProtection="1" applyFont="1" applyBorder="1">
	<alignment horizontal="center"/>
	<protection locked="0"/>
</xf>
```
Excel can open this file normally then. 

Thank you for your contribution, your work has helped me a lot, also hope that this library can be made better.

**Comment by eddiecorrigall** [comment]
I'll take a look. I might be able to control the insertion order so that this does not happen.

**Comment by eddiecorrigall** [comment]
I was able to reproduce this issue.

In Excel:
1. Create new xlsx
2. Select a range of cells
3. Format cells: uncheck locked within Protection tab

Run xlsx-populate code to add a horizontal alignment:
```js
XlsxPopulate
    .fromFileAsync("cell-protection.xlsx")
    .then(workbook => {
        workbook
            .sheet("Sheet1")
            .cell("A1")
            .style("horizontalAlignment", "center");

        return workbook.toFileAsync("./out.xlsx");
    });
```

**Comment by garrensweet** [comment]
Bump. Any progress on this? It's causing some issues in that we're not able to open any of our files with Excel (only open office) which is not a great work around.

**Comment by LesterLyu** [comment]
I will take a look. If I find a fix, I will make a pull request.

**Comment by garrensweet** [comment]
Actually, I've found it was a combination of issues. I managed to work around this one but found another issue. It only impacts excel and not open office.

**Comment by LesterLyu** [comment]
Try if this works: https://github.com/LesterLyu/xlsx-populate/tree/issue-157
```js
npm install https://github.com/LesterLyu/xlsx-populate.git#issue-157
```

**Comment by mdgozza** [comment]
-> Bump here <- 
I ran into this issue as well, I will attempt to debug and maybe suggest a change myself tomorrow, however I've only just started working with xlsx-populate ( my favorite open source repo 😉)

**Comment by mdgozza** [comment]
Update:

I can reproduce this issue when I'm dealing with sheets > 1,000 rows in length and 38 columns wide.

I'm not too sure how to continue debugging, but will try. It does not matter how many styles nor what their value is, if I so much as set all the cells to have a black fill the spreadsheet will not open in excel.

**Comment by mdgozza** [comment]
> Try if this works: https://github.com/LesterLyu/xlsx-populate/tree/issue-157
> 
> ```js
> npm install https://github.com/LesterLyu/xlsx-populate.git#issue-157
> ```

@LesterLyu Afraid that version of xlsx-populate does not solve my problem, if it is the same problem 😅

**Comment by mdgozza** [comment]
I believe I have concluded this issue ( or at least my issue ) to be directly related to #188 . When there are less rows, my workbook opens perfectly fine. I have attempted to set the styles uses ranges instead, but the end result is still the same. 

I will move to that issue.

**Comment by LesterLyu** [comment]
There is a limitation on the number of styles. If it exceeds that number, excel will fail to open. In current implementation, each cell uses a style, even though the styles are same. Ideally those cells should share the same style.

**Comment by Serj-M** [comment]
If you download this excel file from the server side (In my case Node JS). 
The problem is solved by one line on the client side:  **req.responseType = "arraybuffer";**
```
var req = new XMLHttpRequest();
req.open("GET", "http://...", true);
req.responseType = "arraybuffer";
req.onreadystatechange = function () {
    if (req.readyState === 4 && req.status === 200){
        XlsxPopulate.fromDataAsync(req.response)
            .then(function (workbook) {
                // ...
            });
    }
};

req.send();
```

**Comment by curtcommander** [comment]
> There is a limitation on the number of styles. If it exceeds that number, excel will fail to open. In current implementation, each cell uses a style, even though the styles are same. Ideally those cells should share the same style.

I haven't looked under the hood to confirm this, but it looks like you can make cells share the same style like this:

```javascript
const numFormat = ws.cell('C2').style('numberFormat');
ws.range('C2:C10000').style('numberFormat', numFormat);
```

Using this approach resolved the issue for me.

**Comment by natpbs** [comment]
I experienced the same issue and managed to work around it in two ways as follows. 
I hope that the issue is resolved soon so that this information is no longer relevant, in the meanwhile however this could be useful for anyone else experiencing the same problem.

## Method 1 - Manually editing the source excel

The error in the output excel (where an xf cell style tag has the protection children before the alignment children) is caused by xlsx-populate appending the alignment tag at the end of xf's children when one sets, for example, the horizontalAlignment style property to an unstyled cell. However, if an aligment tag is already present in the cell style tag, then it is reused avoiding the mis-ordering. 

For my specific usecase, I needed to unlock only some cells in a sheet in the source file, then style them using xlsx-populate and export the resulting excel. I noticed that if when preparing the input sheet I set at least one alignment property (such as verticalAlignment, horizontalAlignment, textWrap) for all the cells which need to be unlocked, then I don't encounter the issue, since the alignment tag and the protection tag are both alrady present and in the correct order.

## Method 2 - exploiting xlsx-populate's implementation details

If editing the source file to set an alignment property on all of the cells which are unlocked is not feasible, another option is to reorder the alignment and protecton tags manually before exporting the excel as follows, altering xlsx-populate's internal representation of the workbook. I tested this on the current version (1.21.0) but since it uses undocumented implementation details it might break in future versions or even in the current one in some cases. 

Note that the re-ordering must be applied after editing the workbok style and before exporting to excel.

Building on eddiecorrigall's sample from https://github.com/dtjohnson/xlsx-populate/issues/157#issuecomment-463204424, here is the code I used.


```js
XlsxPopulate
    .fromFileAsync("cell-protection.xlsx")
    .then(workbook => {
        workbook
            .sheet("Sheet1")
            .cell("A1")
            .style("horizontalAlignment", "center");

        /* if an xf tag has two or more children, it means that problably 
         * the protection and alignment children tags are in the wrong order. 
         * Here we manually fix the order, so that excel can read the file. */
        workbook._styleSheet._cellXfsNode.children
            .filter((xf) => {
                // only consider xf nodes where the protection tag is before the alignment one
                return (
                    xf.children.length > 1 &&
                    xf.children[0].name === "protection"
                );
            })
            .forEach((xf) => {
                xf.children = xf.children.reverse(); // <-- put "alignment" before "protection"
            })

        return workbook.toFileAsync("./out.xlsx");
    });
```

**Comment by MohammedAshikKP** [comment]
Hey, Does this issue resolved? 
Am still getting the same error in windows while it works perfectly in linux based systems.I have added drop down options (using dataValiadtion) to one of my column and this is not working in windows.
here is my code 

     ` 
        // Create a new workbook
        const workbook = await XlsxPopulate.fromBlankAsync();

        // Define the dynamic drop-down options
        const dropDownOptions = ['red', 'blue', 'green'];

        // Get the first sheet of the workbook
        const sheet = workbook.sheet(0);

        // Set the header row values
        sheet.row(1).cell(1).value('id');
        sheet.row(1).cell(2).value('name');
        sheet.row(1).cell(3).value('type');

        // Apply bold font to the header row
        sheet.row(1).style('bold', true);

        // Set the data validation for each cell in the "type" column
        for (let i = 2; i <= 200; i++) {
            const cell = sheet.cell(`C${i}`);
            cell.dataValidation({
                type: 'list',
                formula1: dropDownOptions.join(','),
                allowBlank: false,
                showInputMessage: false,
                prompt: false,
                promptTitle: 'String',
                showErrorMessage: false,
                
            });
        }

        // Generate the Excel file buffer
        const excelFileBuffer = await workbook.outputAsync();`
